import React from "react";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { Target, ArrowRight, RotateCcw, AlertTriangle, Award, BookOpen, CheckCircle2, Clock, Sparkles, Flame } from "lucide-react";

export const revalidate = 0;
const EXAM_DATE_KEY = "2026-12-06";
function daysUntilExam(now: Date) { const todayKey = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(now); const todayUtc = Date.parse(`${todayKey}T00:00:00Z`); const examUtc = Date.parse(`${EXAM_DATE_KEY}T00:00:00Z`); return Math.max(0, Math.ceil((examUtc - todayUtc) / 86400000)); }

export default async function DashboardPage() {
  const user = await prisma.user.findFirst({ where: { email: "rafael@estudos.transpetro" }, include: { progress: { include: { topic: { include: { subject: true } } } }, simulations: { orderBy: { completedAt: "desc" }, take: 3 } } });
  const subjects = await prisma.subject.findMany({ include: { topics: { include: { userProgress: { where: { userId: user?.id } } } } }, orderBy: { order: "asc" } });
  const userProgressList = user?.progress || [];
  const progressByTopic = new Map(userProgressList.map((progress) => [progress.topicId, progress]));
  const allTopics = subjects.flatMap((subject) => subject.topics);
  const totalTopicsCount = allTopics.length;
  const studiedTopics = allTopics.filter((topic) => progressByTopic.get(topic.id)?.status !== undefined && progressByTopic.get(topic.id)?.status !== "NAO_INICIADO");
  const masteredTopics = allTopics.filter((topic) => progressByTopic.get(topic.id)?.status === "DOMINADO");
  const syllabusProgressPercent = totalTopicsCount > 0 ? Math.round((studiedTopics.length / totalTopicsCount) * 100) : 0;
  const totalMasterySum = allTopics.reduce((acc, topic) => acc + (progressByTopic.get(topic.id)?.masteryScore || 0), 0);
  const averageMastery = totalTopicsCount > 0 ? Math.round(totalMasterySum / totalTopicsCount) : 0;
  const targetScore = user?.targetScore || 47;
  const now = new Date();
  const reviewsDue = userProgressList.filter((p) => p.status === "EM_REVISAO" || (p.nextReviewDate && new Date(p.nextReviewDate) <= now));
  const weakPoints = [...userProgressList].filter((p) => p.status !== "NAO_INICIADO" && p.masteryScore < 70 && allTopics.some((topic) => topic.id === p.topicId)).sort((a, b) => a.masteryScore - b.masteryScore).slice(0, 3);
  const dueTopics = allTopics.filter((topic) => { const progress = progressByTopic.get(topic.id); return Boolean(progress?.nextReviewDate && new Date(progress.nextReviewDate) <= now); }).sort((a, b) => (progressByTopic.get(a.id)?.nextReviewDate?.getTime() ?? 0) - (progressByTopic.get(b.id)?.nextReviewDate?.getTime() ?? 0));
  const dueTopic = dueTopics[0];
  const unstartedTopic = allTopics.find((topic) => !progressByTopic.has(topic.id) || progressByTopic.get(topic.id)?.status === "NAO_INICIADO");
  const weakTopic = weakPoints[0]?.topic;
  const leastRecentlyStudied = [...allTopics].filter((topic) => progressByTopic.has(topic.id)).sort((a, b) => (progressByTopic.get(a.id)?.lastStudiedAt?.getTime() ?? 0) - (progressByTopic.get(b.id)?.lastStudiedAt?.getTime() ?? 0))[0];
  const nextToStudy = dueTopic || unstartedTopic || weakTopic || leastRecentlyStudied || allTopics[0];
  const nextPriorityReason = dueTopic ? "revisão vencida" : unstartedTopic ? "tópico ainda não estudado" : weakTopic ? "menor domínio entre os pontos de atenção" : "retomada do conteúdo menos recente";
  const daysRemaining = daysUntilExam(now);

  return <div className="space-y-6">
    <div className="relative overflow-hidden bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 border border-slate-700/80 rounded-2xl p-5 sm:p-7 shadow-xl"><div className="absolute top-0 right-0 w-80 h-80 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none -mr-20 -mt-20" /><div className="relative z-10"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 pb-4 border-b border-slate-700/60"><div><div className="flex items-center gap-2 flex-wrap"><span className="px-2.5 py-0.5 text-xs font-semibold uppercase tracking-wider bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded-md">Transpetro 2026</span><span className="text-xs text-slate-400 flex items-center gap-1"><Clock className="w-3.5 h-3.5 text-amber-400" /> Prova: 06/12/2026 ({daysRemaining} dias)</span><span className="text-xs text-orange-300 flex items-center gap-1"><Flame className="w-3.5 h-3.5" /> {user?.currentStreak ?? 0} {user?.currentStreak === 1 ? "dia seguido" : "dias seguidos"}</span></div><h1 className="text-xl sm:text-2xl font-bold text-white mt-1">Bons estudos, Rafael. Aqui está seu progresso.</h1></div>{nextToStudy && <Link href={`/aula/${nextToStudy.id}`} className="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-sm shadow-lg shadow-emerald-500/20 transition-all active:scale-95">Continuar de onde parou <span className="sr-only">, {nextPriorityReason}</span><ArrowRight className="w-4 h-4" /></Link>}</div><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-5"><Metric icon={<Target className="w-3.5 h-3.5 text-emerald-400" />} label="Sua Meta" value={targetScore} suffix="/ 60 pts" detail="Acertos desejados no simulado" /><Metric icon={<CheckCircle2 className="w-3.5 h-3.5 text-sky-400" />} label="Domínio Médio" value={`${averageMastery}%`} suffix="" detail="Retenção nos assuntos estudados" /><Metric icon={<BookOpen className="w-3.5 h-3.5 text-amber-400" />} label="Edital Visto" value={`${syllabusProgressPercent}%`} suffix={`(${studiedTopics.length}/${totalTopicsCount})`} detail="Tópicos com teoria ou questões" /><Metric icon={<CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />} label="Tópicos Seguros" value={masteredTopics.length} suffix="tópicos" detail="Rendimento acima de 85%" /></div></div></div>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 flex flex-col justify-between"><div><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wider text-sky-400 flex items-center gap-1.5"><RotateCcw className="w-3.5 h-3.5" /> Revisão do Dia</span><span className="px-2 py-0.5 text-xs font-semibold bg-sky-500/10 text-sky-300 border border-sky-500/20 rounded-full">{reviewsDue.length} pendentes</span></div><h3 className="text-lg font-bold text-white mt-1.5">{reviewsDue.length > 0 ? `${reviewsDue.length} tópicos para revisar hoje` : "Tudo em dia com as revisões!"}</h3><p className="text-xs text-slate-400 mt-1">{reviewsDue.length > 0 ? "Revisar no intervalo certo consolida a memória de longo prazo." : "Nenhum assunto acumulado para hoje. Pode avançar na matéria."}</p></div><div className="mt-4 pt-3 border-t border-slate-800/80 flex items-center justify-between"><Link href="/flashcards" className="inline-flex items-center gap-1.5 text-xs font-semibold text-sky-400">Abrir baralhos <ArrowRight className="w-3.5 h-3.5" /></Link><Link href="/flashcards" className="px-4 py-2 rounded-xl bg-sky-500/15 border border-sky-500/30 text-sky-300 font-semibold text-xs">Revisar agora</Link></div></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 flex flex-col justify-between"><div><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wider text-rose-400 flex items-center gap-1.5"><AlertTriangle className="w-3.5 h-3.5" /> Assuntos Críticos</span><span className="text-xs text-slate-400">Abaixo de 70%</span></div><h3 className="text-lg font-bold text-white mt-1.5">Pontos de Atenção</h3>{weakPoints.length > 0 ? <div className="mt-2.5 space-y-1.5">{weakPoints.map((wp) => <div key={wp.id} className="flex items-center justify-between bg-slate-800/60 px-3 py-1.5 rounded-lg border border-slate-700/50 text-xs"><span className="text-slate-200 truncate pr-2">{wp.topic.code ? `${wp.topic.code} ` : ""}{wp.topic.title}</span><span className="font-bold text-rose-400">{Math.round(wp.masteryScore)}%</span></div>)}</div> : <p className="text-xs text-slate-400 mt-1">Sem pontos críticos no momento. Continue resolvendo questões para calibrar suas métricas.</p>}</div><div className="mt-4 pt-3 border-t border-slate-800/80 flex items-center justify-between"><span className="text-[11px] text-slate-400">Questões focadas onde você mais errou</span><Link href="/questoes?modo=erros" className="px-4 py-2 rounded-xl bg-rose-500/15 border border-rose-500/30 text-rose-300 font-semibold text-xs">Praticar erros</Link></div></div></div>
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="text-base font-bold text-white flex items-center gap-2"><BarChart2Icon className="w-4 h-4 text-emerald-400" />Progresso por Disciplina</h2><p className="text-xs text-slate-400">Acompanhe seu avanço em cada matéria do conteúdo programático</p></div><Link href="/edital" className="text-xs font-semibold text-emerald-400">Ver edital completo <ArrowRight className="w-3.5 h-3.5" /></Link></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{subjects.map((subj) => { const total = subj.topics.length; const completed = subj.topics.filter((topic) => topic.userProgress[0]?.status !== undefined && topic.userProgress[0]?.status !== "NAO_INICIADO").length; const avg = total ? Math.round(subj.topics.reduce((sum, topic) => sum + (topic.userProgress[0]?.masteryScore || 0), 0) / total) : 0; return <div key={subj.id} className="bg-slate-800/70 border border-slate-700/60 rounded-xl p-3.5"><div className="flex items-start justify-between gap-2"><h4 className="text-xs font-bold text-white line-clamp-1">{subj.name}</h4><span className="text-xs font-bold px-1.5 py-0.5 rounded bg-slate-700 text-slate-300">{avg}%</span></div><div className="flex items-center justify-between text-[11px] text-slate-400 mt-2.5"><span>{completed} de {total} tópicos</span><span>{subj.category === "ESPECIFICO" ? "Específica" : "Básica"}</span></div><div className="w-full bg-slate-700/50 rounded-full h-1.5 mt-1.5 overflow-hidden"><div className="bg-emerald-400 h-full rounded-full" style={{ width: `${total > 0 ? Math.round((completed / total) * 100) : 0}%` }} /></div></div>; })}</div></div>
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex items-center justify-between mb-3"><h2 className="text-base font-bold text-white flex items-center gap-2"><Award className="w-4 h-4 text-amber-400" />Últimos Simulados (60 questões)</h2><Link href="/simulado" className="px-3 py-1.5 rounded-lg bg-emerald-500 text-slate-950 font-bold text-xs">Fazer simulado</Link></div>{user?.simulations?.length ? <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-3">{user.simulations.map((sim) => <div key={sim.id} className="bg-slate-800/80 border border-slate-700/70 rounded-xl p-3.5 flex items-center justify-between"><div><p className="text-xs font-semibold text-slate-300">{sim.title}</p><p className="text-[11px] text-slate-500">{new Date(sim.completedAt).toLocaleDateString("pt-BR")}</p></div><div className="text-right"><div className="flex items-baseline gap-1"><span className="text-lg font-black text-white">{Math.round(sim.score)}</span><span className="text-xs text-slate-400">/ 60</span></div><span className="text-[10px] text-slate-400">Sua meta: {targetScore}/60</span></div></div>)}</div> : <div className="text-center py-6 border border-dashed border-slate-800 rounded-xl"><p className="text-xs text-slate-400">Nenhum simulado realizado até o momento.</p><Link href="/simulado" className="inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-400 mt-2"><Sparkles className="w-3.5 h-3.5" />Iniciar primeiro simulado</Link></div>}</div>
  </div>;
}
function Metric({ icon, label, value, suffix, detail }: { icon: React.ReactNode; label: string; value: React.ReactNode; suffix: string; detail: string }) { return <div className="bg-slate-800/80 border border-slate-700/60 rounded-xl p-3.5"><p className="text-xs text-slate-400 font-medium flex items-center gap-1">{icon}{label}</p><div className="mt-1 flex items-baseline gap-1"><span className="text-2xl font-black text-white">{value}</span>{suffix && <span className="text-xs text-slate-400">{suffix}</span>}</div><p className="text-[11px] text-slate-400 mt-1">{detail}</p></div>; }
function BarChart2Icon(props: React.SVGProps<SVGSVGElement>) { return <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" x2="18" y1="20" y2="10" /><line x1="12" x2="12" y1="20" y2="4" /><line x1="6" x2="6" y1="20" y2="6" /></svg>; }
