"use client";
import React,{useEffect,useRef,useState}from"react";
import Link from"next/link";
import{toast}from"sonner";
import{Clock,CheckCircle2,AlertTriangle,Award,ChevronLeft,ChevronRight,Send,Flag}from"lucide-react";
import type{ExamDiagnostic}from"@/lib/exam";

export const SimulationExam=({questions}:{questions:any[]})=>{
 const [index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[flags,setFlags]=useState<Record<string,boolean>>({}),[left,setLeft]=useState(14400),[submitted,setSubmitted]=useState(false),[sending,setSending]=useState(false),[diagnostic,setDiagnostic]=useState<ExamDiagnostic|null>(null);
 const answersRef=useRef(answers),leftRef=useRef(left),submittedRef=useRef(false),sendingRef=useRef(false),questionStartedAtRef=useRef(Date.now()),questionTimesRef=useRef<Record<string,number>>({}),submissionKeyRef=useRef("");
 answersRef.current=answers;leftRef.current=left;submittedRef.current=submitted;sendingRef.current=sending;
 const q=questions[index];
 const recordCurrentQuestionTime=()=>{const current=q;if(!current)return;const elapsed=Math.max(0,Math.floor((Date.now()-questionStartedAtRef.current)/1000));questionTimesRef.current[current.id]=(questionTimesRef.current[current.id]||0)+elapsed;questionStartedAtRef.current=Date.now();};
  const submit=async(force=false)=>{
   if(sendingRef.current||submittedRef.current)return;
   recordCurrentQuestionTime();
   const currentAnswers=answersRef.current,currentLeft=leftRef.current,answered=Object.keys(currentAnswers).length;
   if(!force&&answered<60&&currentLeft>60&&!window.confirm(`Você marcou ${answered} das 60 questões. Deseja entregar o simulado agora mesmo com questões em branco?`))return;
   if(!submissionKeyRef.current)submissionKeyRef.current=crypto.randomUUID();
   sendingRef.current=true;setSending(true);
   try{
    const res=await fetch("/api/simulado",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:`Simulado Transpetro 2026.3 #${new Date().toLocaleDateString("pt-BR")}`,durationSeconds:14400-currentLeft,answers:currentAnswers,questionIds:questions.map(x=>x.id),questionTimes:questionTimesRef.current,idempotencyKey:submissionKeyRef.current})});
    const data=await res.json();if(!res.ok)throw new Error(data.error||"Não foi possível salvar o simulado.");
    submittedRef.current=true;setDiagnostic(data.diagnostic);setSubmitted(true);toast.success(data.duplicate?"Simulado recuperado com sucesso.":"Prova entregue! Confira seu desempenho abaixo.");
   }catch(e:any){toast.error(e.message||"Erro ao enviar o simulado. Verifique sua conexão e tente novamente.");}finally{sendingRef.current=false;setSending(false);}
  };
  useEffect(()=>{if(submitted)return;const t=setInterval(()=>setLeft(v=>{if(v<=1){clearInterval(t);leftRef.current=0;void submit(true);return 0}const next=v-1;leftRef.current=next;return next}),1000);return()=>clearInterval(t)},[submitted]);
  useEffect(()=>{questionStartedAtRef.current=Date.now();return()=>{recordCurrentQuestionTime()}},[index]);
  const time=(s:number)=>`${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor(s%3600/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
  if(submitted&&diagnostic)return <div className="max-w-2xl mx-auto bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-6"><div className="text-center"><Award className="w-10 h-10 mx-auto text-emerald-400"/><h2 className="text-2xl font-black text-white mt-2">Desempenho no Simulado</h2><p className="text-xs text-slate-400">Transpetro 2026.3 • Ênfase 18</p></div><div className="text-center bg-slate-800 rounded-xl p-5"><p className="text-xs text-slate-400 uppercase">Pontuação Final</p><p className="text-4xl font-black text-white"><span className={diagnostic.isEliminated?"text-rose-400":diagnostic.isAboveTarget?"text-emerald-400":"text-amber-400"}>{diagnostic.totalScore}</span><span className="text-lg text-slate-400"> / 60</span></p><p className="text-xs text-slate-400 mt-1">Sua meta definida: {diagnostic.targetScore}/60</p></div>{diagnostic.isEliminated?<div className="bg-rose-950/40 border border-rose-800 rounded-xl p-4"><div className="flex gap-2 text-rose-400 font-bold text-xs"><AlertTriangle className="w-4 h-4"/> Atenção aos critérios do edital</div>{diagnostic.eliminationReasons.map((r,i)=><p key={i} className="text-xs text-rose-200 mt-1">• {r}</p>)}</div>:<div className="bg-emerald-950/30 border border-emerald-800 rounded-xl p-4 text-xs text-emerald-300 flex gap-2"><CheckCircle2 className="w-4 h-4"/> Você atingiu a pontuação mínima exigida pelo edital.</div>}<div className="grid grid-cols-3 gap-3">{[["Português",diagnostic.breakdown.portugueseScore,10],["Matemática",diagnostic.breakdown.mathScore,10],["Específicas",diagnostic.breakdown.specificScore,40]].map(([n,s,t])=><div key={n as string} className="bg-slate-800 rounded-xl p-3 text-center"><p className="text-[11px] text-slate-400">{n}</p><p className="text-base font-bold text-white">{s}/{t}</p></div>)}</div><div className="flex justify-center gap-3"><Link href="/simulado" className="px-4 py-2 rounded-xl bg-slate-800 text-slate-300 text-xs font-semibold">Ver Histórico</Link><Link href="/" className="px-5 py-2 rounded-xl bg-emerald-500 text-slate-950 text-xs font-bold">Voltar ao Início</Link></div></div>;
   const getSectionInfo = (qIdx: number) => {
     if (qIdx < 10) return { title: "Língua Portuguesa", badge: "bg-sky-500/10 text-sky-400 border-sky-500/30" };
     if (qIdx < 20) return { title: "Matemática", badge: "bg-amber-500/10 text-amber-400 border-amber-500/30" };
     return { title: "Conhecimentos Específicos", badge: "bg-emerald-500/10 text-emerald-400 border-emerald-500/30" };
   };

  return <div className="max-w-4xl mx-auto space-y-5 pb-28 sm:pb-16"><div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 flex justify-between items-center"><div><span className="text-xs font-bold text-emerald-400">Simulado Cesgranrio • 60 Questões</span><p className="text-xs text-slate-400">Respondidas: <b className="text-white">{Object.keys(answers).length}</b> de 60</p></div><div className="flex gap-3 items-center"><span className={`px-3 py-1.5 rounded-full border text-xs font-bold ${left<1800?"text-rose-400 border-rose-500/40":"text-amber-400 border-slate-700"}`}><Clock className="w-3.5 h-3.5 inline mr-1"/>{time(left)}</span><button onClick={()=>void submit()} disabled={sending||submitted} className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs disabled:opacity-50 disabled:cursor-not-allowed transition-colors"><Send className="w-3.5 h-3.5 inline mr-1"/>{sending?"Entregando...":"Entregar Prova"}</button></div></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-3 flex flex-wrap gap-1.5">{questions.map((x,i)=>{
     const isPort = i < 10;
     const isMath = i >= 10 && i < 20;
     return <button key={x.id} onClick={()=>setIndex(i)} disabled={sending||submitted} className={`w-7 h-7 rounded-md border text-[11px] font-bold disabled:opacity-70 transition-all ${i===index?"ring-2 ring-emerald-400 border-white scale-105":isPort?"border-sky-800/80":isMath?"border-amber-800/80":"border-slate-700"} ${answers[x.id]?"bg-emerald-500/30 text-emerald-300":"bg-slate-800 text-slate-400"}`}>{i+1}</button>;
   })}</div>{q&&<div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 sm:p-7 space-y-5"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 pb-3"><div className="flex items-center gap-2 flex-wrap"><span className="text-xs font-bold text-slate-200">Questão {index+1} de 60</span><span className={`text-[10px] px-2 py-0.5 rounded border font-semibold ${getSectionInfo(index).badge}`}>{getSectionInfo(index).title}</span></div><button onClick={()=>setFlags(f=>({...f,[q.id]:!f[q.id]}))} disabled={sending||submitted} className="text-xs text-slate-400 hover:text-amber-300 disabled:opacity-50 transition-colors"><Flag className={`w-3.5 h-3.5 inline mr-1 ${flags[q.id] ? "text-amber-400 fill-amber-400" : ""}`}/>{flags[q.id]?"Marcada para revisão":"Marcar para rever"}</button></div><p className="text-sm sm:text-base text-slate-100 font-medium leading-relaxed whitespace-pre-line">{q.statement}</p><div className="space-y-2">{["A","B","C","D","E"].map(o=>q[`option${o}`]?<button key={o} onClick={()=>setAnswers(a=>({...a,[q.id]:o}))} disabled={sending||submitted} className={`w-full text-left p-3 rounded-xl border text-sm flex gap-3 transition-colors disabled:opacity-70 ${answers[q.id]===o?"bg-emerald-500/20 border-emerald-500 text-white":"bg-slate-800/70 hover:bg-slate-800 border-slate-700 text-slate-300"}`}><b>{o}</b><span>{q[`option${o}`]}</span></button>:null)}</div><div className="flex justify-between pt-2"><button onClick={()=>setIndex(i=>Math.max(0,i-1))} disabled={index===0||sending||submitted} className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium disabled:opacity-30 transition-colors"><ChevronLeft className="w-4 h-4 inline"/> Anterior</button><button onClick={()=>setIndex(i=>Math.min(59,i+1))} disabled={index===59||sending||submitted} className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium disabled:opacity-30 transition-colors">Próxima <ChevronRight className="w-4 h-4 inline"/></button></div></div>}</div>;
};
