"use client";
import React,{useEffect,useState}from"react";
import Link from"next/link";
import{toast}from"sonner";
import{Clock,CheckCircle2,AlertTriangle,Award,ChevronLeft,ChevronRight,Send,Flag}from"lucide-react";
import type{ExamDiagnostic}from"@/lib/exam";

export const SimulationExam=({questions}:{questions:any[]})=>{
 const [index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[flags,setFlags]=useState<Record<string,boolean>>({}),[left,setLeft]=useState(14400),[submitted,setSubmitted]=useState(false),[sending,setSending]=useState(false),[diagnostic,setDiagnostic]=useState<ExamDiagnostic|null>(null);
 const q=questions[index];
 const submit=async(force=false)=>{
  if(sending||submitted)return;
  const answered=Object.keys(answers).length;
  if(!force&&answered<60&&left>60&&!window.confirm(`Você respondeu ${answered} de 60 questões. Deseja finalizar?`))return;
  setSending(true);
  try{
   const res=await fetch("/api/simulado",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:`Simulado Transpetro 2026.3 #${new Date().toLocaleDateString("pt-BR")}`,durationSeconds:14400-left,answers,questionIds:questions.map(x=>x.id)})});
   const data=await res.json();if(!res.ok)throw new Error(data.error||"Erro ao salvar simulado.");
   setDiagnostic(data.diagnostic);setSubmitted(true);toast.success("Simulado concluído!");
  }catch(e:any){toast.error(e.message||"Falha ao enviar simulado.");}finally{setSending(false);}
 };
 useEffect(()=>{if(submitted)return;const t=setInterval(()=>setLeft(v=>{if(v<=1){clearInterval(t);void submit(true);return 0}return v-1}),1000);return()=>clearInterval(t)},[submitted]);
 const time=(s:number)=>`${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor(s%3600/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
 if(submitted&&diagnostic)return <div className="max-w-2xl mx-auto bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-6"><div className="text-center"><Award className="w-10 h-10 mx-auto text-emerald-400"/><h2 className="text-2xl font-black text-white mt-2">Resultado do Simulado</h2><p className="text-xs text-slate-400">TRANSPETRO 2026.3 • Ênfase 18</p></div><div className="text-center bg-slate-800 rounded-xl p-5"><p className="text-xs text-slate-400 uppercase">Pontuação</p><p className="text-4xl font-black text-white"><span className={diagnostic.isEliminated?"text-rose-400":diagnostic.isAboveTarget?"text-emerald-400":"text-amber-400"}>{diagnostic.totalScore}</span><span className="text-lg text-slate-400"> / 60</span></p><p className="text-xs text-slate-400 mt-1">Meta pessoal: {diagnostic.targetScore}/60</p></div>{diagnostic.isEliminated?<div className="bg-rose-950/40 border border-rose-800 rounded-xl p-4"><div className="flex gap-2 text-rose-400 font-bold text-xs"><AlertTriangle className="w-4 h-4"/> CRITÉRIO DE ELIMINAÇÃO</div>{diagnostic.eliminationReasons.map((r,i)=><p key={i} className="text-xs text-rose-200 mt-1">• {r}</p>)}</div>:<div className="bg-emerald-950/30 border border-emerald-800 rounded-xl p-4 text-xs text-emerald-300 flex gap-2"><CheckCircle2 className="w-4 h-4"/> Critérios mínimos de eliminação superados.</div>}<div className="grid grid-cols-3 gap-3">{[["Português",diagnostic.breakdown.portugueseScore,10],["Matemática",diagnostic.breakdown.mathScore,10],["Específicas",diagnostic.breakdown.specificScore,40]].map(([n,s,t])=><div key={n as string} className="bg-slate-800 rounded-xl p-3 text-center"><p className="text-[11px] text-slate-400">{n}</p><p className="text-base font-bold text-white">{s}/{t}</p></div>)}</div><div className="flex justify-center gap-3"><Link href="/simulado" className="px-4 py-2 rounded-xl bg-slate-800 text-slate-300 text-xs font-semibold">Histórico</Link><Link href="/" className="px-5 py-2 rounded-xl bg-emerald-500 text-slate-950 text-xs font-bold">Início</Link></div></div>;
 return <div className="max-w-4xl mx-auto space-y-5 pb-16"><div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 flex justify-between items-center"><div><span className="text-xs font-bold text-emerald-400">SIMULADO TRANSPETRO • 60 QUESTÕES</span><p className="text-xs text-slate-400">Respondidas: <b className="text-white">{Object.keys(answers).length}</b>/60</p></div><div className="flex gap-3 items-center"><span className={`px-3 py-1.5 rounded-full border text-xs font-bold ${left<1800?"text-rose-400 border-rose-500/40":"text-amber-400 border-slate-700"}`}><Clock className="w-3.5 h-3.5 inline mr-1"/>{time(left)}</span><button onClick={()=>void submit()} disabled={sending} className="px-4 py-2 rounded-xl bg-emerald-500 text-slate-950 font-bold text-xs"><Send className="w-3.5 h-3.5 inline mr-1"/>Finalizar</button></div></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-3 flex flex-wrap gap-1.5">{questions.map((x,i)=><button key={x.id} onClick={()=>setIndex(i)} className={`w-7 h-7 rounded-md border text-[11px] font-bold ${i===index?"ring-2 ring-emerald-400 border-white":"border-slate-700"} ${answers[x.id]?"bg-emerald-500/30 text-emerald-300":"bg-slate-800 text-slate-400"}`}>{i+1}</button>)}</div>{q&&<div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 sm:p-7 space-y-5"><div className="flex justify-between border-b border-slate-800 pb-3"><span className="text-xs font-bold text-slate-200">Questão {index+1} de 60</span><button onClick={()=>setFlags(f=>({...f,[q.id]:!f[q.id]}))} className="text-xs text-slate-400"><Flag className="w-3.5 h-3.5 inline mr-1"/>{flags[q.id]?"Marcada":"Marcar"}</button></div><p className="text-sm sm:text-base text-slate-100 font-medium leading-relaxed whitespace-pre-line">{q.statement}</p><div className="space-y-2">{["A","B","C","D","E"].map(o=>q[`option${o}`]?<button key={o} onClick={()=>setAnswers(a=>({...a,[q.id]:o}))} className={`w-full text-left p-3 rounded-xl border text-sm flex gap-3 ${answers[q.id]===o?"bg-emerald-500/20 border-emerald-500 text-white":"bg-slate-800/70 border-slate-700 text-slate-300"}`}><b>{o}</b><span>{q[`option${o}`]}</span></button>:null)}</div><div className="flex justify-between"><button onClick={()=>setIndex(i=>Math.max(0,i-1))} disabled={index===0} className="px-4 py-2 rounded-xl bg-slate-800 text-slate-300 text-xs disabled:opacity-30"><ChevronLeft className="w-4 h-4 inline"/> Anterior</button><button onClick={()=>setIndex(i=>Math.min(59,i+1))} disabled={index===59} className="px-4 py-2 rounded-xl bg-slate-800 text-slate-300 text-xs disabled:opacity-30">Próxima <ChevronRight className="w-4 h-4 inline"/></button></div></div>}</div>;
};
